name: Byg skoler.json automatisk (minimal)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer afhængigheder
        run: pip install pandas chardet

      # Kør Python direkte (ingen heredoc/EOF)
      - name: Generer skoler.json (uden geokodning)
        shell: python
        run: |
          import pandas as pd, json, pathlib
          from chardet import detect

          csv_path = pathlib.Path("data/folkeskoler.csv")
          raw = csv_path.read_bytes()
          enc = detect(raw)["encoding"] or "latin1"

          # Læs CSV robust (auto-separator + encoding)
          df = pd.read_csv(csv_path, sep=None, engine="python", encoding=enc, low_memory=False)
          df.columns = [c.strip().lower() for c in df.columns]

          def pick(*names):
              for n in names:
                  if n in df.columns: 
                      return n

          col_inst = pick("institutionsnummer","instnr","institutionnummer")
          col_navn = pick("institutionsnavn","navn","institution")
          col_vej  = pick("vejnavn","adresse","vej")
          col_hus  = pick("husnr","husnummer","nr")
          col_post = pick("postnr","postnummer")
          col_by   = pick("bynavn","by","postdistrikt")
          col_kom  = pick("kommunenavn","kommune")

          rows = []
          for _, r in df.head(300).iterrows():  # første 300 som test
              adr = f"{r.get(col_vej,'')} {r.get(col_hus,'')}, {r.get(col_post,'')} {r.get(col_by,'')}".replace("  "," ").strip(", ").strip()
              rows.append({
                  "id": str(r.get(col_inst,"") or ""),
                  "navn": str(r.get(col_navn,"") or ""),
                  "adresse": adr,
                  "postnr": str(r.get(col_post,"") or ""),
                  "by": str(r.get(col_by,"") or ""),
                  "kommune_navn": str(r.get(col_kom,"") or ""),
                  "region_navn": "",
                  "lon": None,
                  "lat": None
              })

          pathlib.Path("data/skoler.json").write_text(
              json.dumps(rows, ensure_ascii=False, indent=2),
              encoding="utf-8"
          )
          print("✅ Skrev", len(rows), "rækker til data/skoler.json")

      - name: Commit & Push
        run: |
          git config user.name "Auto Data Bot"
          git config user.email "bot@example.com"
          git add data/skoler.json
          git commit -m "Opdater skoler.json (minimal build)" || echo "Ingen ændringer"
          git push
